targets:
  drift:
    auto_apply_builders: false
    builders:
      drift_dev:analyzer:
        enabled: true
        options: &options
          has_separate_analyzer: true # Required for not_shared
          schema_dir: drift_schemas/
          store_date_time_values_as_text: true
          databases:
            database: lib/src/features/database/models/database.dart
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
                - fts5
        generate_for: &generate_for
          include:
            - lib/**database/**.dart
          exclude:
            - lib/**.g.dart
            - lib/**.freezed.dart
      drift_dev:not_shared:
        options: *options
        generate_for: *generate_for

  $default:
    dependencies:
      - ":drift"
    builders:
      drift_dev:
        enabled: false # Disabled since it is handled above.
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/**models/**.dart
          exclude:
            - lib/**.g.dart
            - lib/**.freezed.dart
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**models/**.dart
          exclude:
            - lib/**.g.dart
            - lib/**.freezed.dart
      riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/**providers/**.dart
          exclude:
            - lib/**.g.dart
            - lib/**.freezed.dart
