name: autosteering
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    async: ^2.11.0
    collection: ^1.17.1
    connectivity_plus: ^5.0.2
    cupertino_icons: ^1.0.6
    device_preview: ^1.1.0
    dio: ^5.4.1
    equatable: ^2.0.5
    fast_cached_network_image: ^1.2.8
    file_picker: ^6.2.0
    flex_color_scheme: ^7.3.1
    flutter:
        sdk: flutter
    flutter_libserialport: ^0.4.0
    flutter_map: ^6.1.0
    flutter_riverpod: ^3.0.0-dev.3
    flutter_shaders: ^0.1.2
    freezed_annotation: ^2.4.1
    # gamepads: ^0.1.1
    geobase: ^1.0.0
    geolocator: ^11.0.0
    http: ^1.2.1
    json_annotation: ^4.8.1
    latlong2: ^0.9.0
    logger: ^2.1.0
    nmea: ^3.2.0
    path_provider: ^2.1.2
    permission_handler: ^11.3.0
    riverpod_annotation: ^3.0.0-dev.3
    svg_path_parser: ^1.1.2
    themed: ^5.0.1
    udp: ^5.0.3
    universal_html: ^2.2.4
    universal_io: ^2.2.2
    # usb_serial: ^0.5.1
    uuid: ^4.3.3
    wakelock_plus: ^1.1.4
    web_socket_channel: ^2.4.4
    window_manager: ^0.3.8
    xml: ^6.5.0

dev_dependencies:
    build_runner: ^2.4.8
    custom_lint: ^0.5.11
    flutter_test:
        sdk: flutter
    freezed: ^2.4.7
    json_serializable: ^6.7.1
    riverpod_generator: ^3.0.0-dev.11
    riverpod_lint: ^3.0.0-dev.4
    very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    assets:
        - assets/
        - assets/egm/
        - assets/images/
        - assets/images/vehicle_types/side_view/
        - assets/images/vehicle_types/top_view/

    shaders:
        - assets/shaders/glow.frag
