name: autosteering
description: Prototype program for automatically steering a tractor in a field.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
    sdk: ">=3.6.0 <4.0.0"

dependencies:
    archive: ^4.0.2
    async: ^2.11.0
    audioplayers: ^6.1.0
    collection: ^1.19.0
    cupertino_icons: ^1.0.8
    dio: ^5.7.0
    equatable: ^2.0.7
    fast_cached_network_image: ^1.2.9
    file_picker: ^8.1.7
    fl_chart: ^0.70.0
    flex_color_scheme: ^8.1.0
    flutter:
        sdk: flutter
    flutter_libserialport: ^0.4.0
    flutter_map: ^7.0.2
    flutter_riverpod: ^2.6.1
    flutter_shaders: ^0.1.3
    flutter_svg: ^2.0.10+1
    freezed_annotation: ^2.4.4
    # gamepads: ^0.1.4
    geobase: ^1.4.0
    geolocator: ^13.0.2
    google_fonts: ^6.2.1
    http: ^1.2.2
    intl: ^0.20.1
    json_annotation: ^4.9.0
    latlong2: ^0.9.1
    logger: ^2.5.0
    material_symbols_icons: ^4.2801.1
    nmea: ^3.3.2
    path: ^1.9.0
    path_provider: ^2.1.5
    permission_handler: ^11.3.1
    quiver: ^3.2.2
    riverpod_annotation: ^2.6.1
    themed: ^8.0.2
    udp: ^5.0.3
    universal_html: ^2.2.4
    universal_io: ^2.2.2
    # usb_serial: ^0.5.1
    uuid: ^4.5.1
    wakelock_plus: ^1.2.10
    window_manager: ^0.4.3
    xml: ^6.5.0

dependency_overrides:
    flutter_libserialport:
        git:
            url: https://github.com/snabble/flutter_libserialport.git
            ref: 0.5.0
    universal_io:
        git: 
            url: https://github.com/dint-dev/universal_io.git   
            ref: 41df5f997ffb8e177a06e1be2b539227dbc860ac

dev_dependencies:
    build_runner: ^2.4.14
    custom_lint: ^0.7.0
    flutter_test:
        sdk: flutter
    freezed: ^2.5.7
    json_serializable: ^6.9.0
    riverpod_generator: ^2.6.3
    riverpod_lint: ^2.6.3
    very_good_analysis: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    assets:
        - assets/
        - assets/audio/
        - assets/icons/
        - assets/images/
        - assets/images/vehicle_types/side_view/
        - assets/images/vehicle_types/top_view/
        - google_fonts/

    shaders:
        - assets/shaders/glow.frag
